apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-network
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-aws-network
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: index.docker.io/ulucinar/provider-family-aws
      version: "v0.45.0-046b7555fce31c91824c3b7c06a1c3a2ba945b06"
    - provider: index.docker.io/ulucinar/provider-aws-ec2
      version: "v0.45.0-046b7555fce31c91824c3b7c06a1c3a2ba945b06"
    - function: xpkg.upbound.io/upbound/function-patch-and-transform
      version: "v0.2.1"
